# Site settings
title: CodeAndDrive.com
url: "http://www.CodeAndDrive.com"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "" # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
timezone: Europe/Warsaw
encoding: UTF-8
description: Tomasz Sułkowski - Software developer, Drift racing driver
 
# Your information
email: tomasz_sulkowski@wp.pl
author: Tomasz Sułkowski
avatar: "/assets/images/avatar.jpg"
profile: Software developer, Drift racing driver
#twitter_username: twitter_username
#github_username:  github_username

include: ['assets']
exclude: ["LICENSE.txt", "README.md"]

highlighter: rouge
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge

permalink: /:title

# Plugins
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji
 - jekyll-multiple-languages-plugin
 
# Paginate
paginate: 5
paginate_path: "page:num"

# jekyll-multiple-languages-plugin settings:
languages: ["en", "pl"]
exclude_from_localizations: ["assets", "images", "css", "js"]
