# Site settings
title: CodeAndDrive.com
url: "http://www.CodeAndDrive.com"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "" # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
timezone: Europe/Warsaw
encoding: utf-8
description: Tomasz Sułkowski - .NET developer, Drifting racing driver.
 
# Your information
email: tomasz_sulkowski@wp.pl
author: Tomasz Sułkowski
avatar: "/assets/images/avatar.jpg"
profile: Software developer, Drift racing driver
#twitter_username: twitter_username
#github_username:  github_username

# Comment Service (Disqus or 多说)
#  choose one and un-comment the line to active it
#disqus_shortname: xxx   # get one: https://disqus.com/admin/signup/
#duoshuo_shortname: xxx  # get one: http://duoshuo.com/create-site/

include: ['assets']

permalink: /posts/:title
gems:
 - jekyll-paginate
 - jekyll-gist
 - jemoji
 - jekyll-language-plugin
 
# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

language_data: data.lang.%%
language_includes_dir: _i18n
languages: ['en', 'pl']

kramdown:
  input: GFM
  syntax_highlighter: rouge
