# Site settings
title: CodeAndDrive.com
url: "http://www.CodeAndDrive.com"    # the protocol and hostname of your site, eg. `http://laobubu.github.io`
baseurl: "" # the prefix of your site uri, eg. `/jekyll-theme-EasyBook` or just one slash `/`
timezone: Europe/Warsaw
encoding: UTF-8
description: Tomasz Sułkowski - Software developer, Drift racing driver
 
# Your information
email: tomasz_sulkowski@wp.pl
author: Tomasz Sułkowski
avatar: "/assets/images/avatar.jpg"
profile: Software developer, Drift racing driver
#twitter_username: twitter_username
#github_username:  github_username

include: ['assets']

permalink: /posts/:lang/:title
plugins:
 - jekyll-paginate
 - jekyll-gist
 - jemoji
 - jekyll-multiple-languages-plugin
 
# Build settings
paginate: 5
paginate_path: "page:num"

highlighter: rouge
markdown: kramdown

language_data: data.lang.%%
language_includes_dir: _i18n
languages:
  - en
  - pl
default_lang: en
exclude_from_localizations:
  - assets/
  - images/
  - _data/

kramdown:
  input: GFM
  syntax_highlighter: rouge
